runtime: go
api_version: go1

handlers:

# If the path is empty, show static index.html file
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

# Otherwise, find file in static directory
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always
